-- 1번 연동: 오늘의 스코어 · 오늘의 약점(Worst 3)용 테이블
-- Supabase 대시보드 → SQL Editor에서 이 전체를 붙여넣고 Run

-- 테이블 생성 (문제 풀이마다 1행 저장)
CREATE TABLE IF NOT EXISTS public.answer_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id TEXT NOT NULL,
  student_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  tag TEXT,
  correct BOOLEAN NOT NULL
);

-- 인덱스 (모니터에서 "오늘 + 학생별" 조회 빠르게)
CREATE INDEX IF NOT EXISTS idx_answer_logs_student_created
  ON public.answer_logs (student_id, created_at DESC);

-- RLS: 익명(anon)으로 insert/select 허용 (똑패스 앱에서 넣고, 모니터에서 읽음)
ALTER TABLE public.answer_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "answer_logs allow anon insert" ON public.answer_logs;
CREATE POLICY "answer_logs allow anon insert" ON public.answer_logs
  FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "answer_logs allow anon select" ON public.answer_logs;
CREATE POLICY "answer_logs allow anon select" ON public.answer_logs
  FOR SELECT TO anon USING (true);
