-- PART 1. 학생 모니터링 사건 기록 저장소
-- Supabase 대시보드 → SQL Editor에서 실행

CREATE TABLE IF NOT EXISTS public.status_logs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id    text,
  student_name  text NOT NULL,
  event_type    text NOT NULL,
  message       text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_status_logs_created_at
  ON public.status_logs (created_at DESC);

ALTER TABLE public.status_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "status_logs_insert_anon" ON public.status_logs;
CREATE POLICY "status_logs_insert_anon" ON public.status_logs
  FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "status_logs_select_anon" ON public.status_logs;
CREATE POLICY "status_logs_select_anon" ON public.status_logs
  FOR SELECT TO anon USING (true);

-- 실시간 반영: Database → Replication 에서 status_logs 복제 활성화
