-- 오늘의 연구 「다시보기」 테이블 (monitor-app snippets — tokpass-app/migrations 와 동일)
-- Supabase SQL Editor에서 실행

CREATE TABLE IF NOT EXISTS public.daily_research_saved_questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  question_id text NOT NULL,
  saved_date_kst text NOT NULL,
  question_type text,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  saved_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, question_id)
);

CREATE INDEX IF NOT EXISTS idx_dr_saved_user_saved_at
  ON public.daily_research_saved_questions (user_id, saved_at DESC);

CREATE INDEX IF NOT EXISTS idx_dr_saved_user_date
  ON public.daily_research_saved_questions (user_id, saved_date_kst DESC);

ALTER TABLE public.daily_research_saved_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "dr_saved_anon_select" ON public.daily_research_saved_questions;
CREATE POLICY "dr_saved_anon_select" ON public.daily_research_saved_questions
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "dr_saved_anon_insert" ON public.daily_research_saved_questions;
CREATE POLICY "dr_saved_anon_insert" ON public.daily_research_saved_questions
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "dr_saved_anon_update" ON public.daily_research_saved_questions;
CREATE POLICY "dr_saved_anon_update" ON public.daily_research_saved_questions
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "dr_saved_anon_delete" ON public.daily_research_saved_questions;
CREATE POLICY "dr_saved_anon_delete" ON public.daily_research_saved_questions
  FOR DELETE TO anon, authenticated USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_research_saved_questions TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
